apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockwatcher-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockwatcher-backend
  template:
    metadata:
      labels:
        app: stockwatcher-backend
    spec:
      containers:
        - image: stockwatcher
          name: stockwatcher
          imagePullPolicy: IfNotPresent
          resources: {}
          ports:
            - containerPort: 5001
